### ISSUE TITLE
Request for Compiled Mod File

### ISSUE THREAD

**Issue by HOOOOOH** [Istyu/Return-of-zombie-ops#1]
I hope this message finds you well. I recently came across your mod code on GitHub for cod4 and I'm really excited to try it out. However, I'm facing some difficulties in compiling the mod myself. I was wondering if it would be possible for you to provide a compiled version of the mod file.
Thank you for your time and consideration.

**Comment by Istyu** [comment]
Hi dear HOOOOOH!
Can we continue contact via discord?

HOOOOOH ***@***.***> ezt írta (időpont: 2023. dec. 5., K,
13:34):

**Comment by HOOOOOH** [comment]
I have found this module, thank you for your reply
